{
 "title": "prediction dashboard",
 "time": { "from": "2024-11-08T19:39:00.000Z", "to": "2024-11-08T21:44:00.000Z" },
 "panels": [
  {
   "title": "loan approvals/rejections vs loan amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN result = 'Approved' THEN 'Loan Approved'\r\n        WHEN result = 'Rejected' THEN 'Loan Rejected'\r\n    END AS loan_status,\r\n    CASE \r\n        WHEN loan_amount < 100000 THEN 'Low Loan Amount'\r\n        WHEN loan_amount BETWEEN 100000 AND 500000 THEN 'Medium Loan Amount'\r\n        ELSE 'High Loan Amount'\r\n    END AS loan_amount_range,\r\n    COUNT(*) AS count\r\nFROM \r\n    loan_prediction\r\nGROUP BY \r\n    loan_status, loan_amount_range\r\nORDER BY \r\n    loan_status, loan_amount_range;\r\n"
    }
   ]
  },
  {
   "title": "Loan Approval vs. Rejection by CIBIL Score Range",
   "type": "piechart",
   "description": "This chart reveals loan approval trends based on CIBIL score categories (High, Medium, Low), highlighting how creditworthiness impacts loan outcomes. It offers quick insights for adjusting lending strategies and identifying areas where applicants may benefit from credit improvement.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN result = 'Approved' THEN 'Loan Approved'\r\n        WHEN result = 'Rejected' THEN 'Loan Rejected'\r\n    END AS loan_status,\r\n    CASE \r\n        WHEN cibil_score >= 750 THEN 'High'\r\n        WHEN cibil_score >= 600 THEN 'Medium'\r\n        ELSE 'Low'\r\n    END AS cibil_score_range,\r\n    COUNT(*) AS count\r\nFROM \r\n    loan_prediction\r\nGROUP BY \r\n    loan_status, cibil_score_range\r\nORDER BY \r\n    loan_status, cibil_score_range;\r\n"
    }
   ]
  },
  {
   "title": "Number of Predictions Over Time (Last 30 Minutes)",
   "type": "barchart",
   "description": "This graph is useful for understanding the model’s load and verifying that predictions are consistently generated. A sudden drop to zero predictions could indicate a system or ingestion failure",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    date_trunc('minute', created_at) AS time,\r\n    COUNT(*) AS prediction_count\r\nFROM \r\n    loan_prediction\r\nWHERE \r\n    created_at >= NOW() - INTERVAL '24 hours'  -- Adjusted interval for testing\r\nGROUP BY \r\n    time\r\nORDER BY \r\n    time;\r\n"
    }
   ]
  },
  {
   "title": "Average Prediction Value in the Last 10 Minutes",
   "type": "timeseries",
   "description": "This graph shows the average prediction outcome over the last 10 minutes. By averaging \"Approved\" (as 1) and \"Rejected\" (as 0 A high average close to 1 means a high rate of approvals, whereas a lower value close to 0 indicates more rejections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    date_trunc('minute', created_at) AS time,\r\n    AVG(\r\n        CASE \r\n            WHEN result = 'Approved' THEN 1\r\n            WHEN result = 'Rejected' THEN 0\r\n            ELSE NULL\r\n        END\r\n    ) AS avg_prediction,\r\n    CASE \r\n        WHEN AVG(\r\n                CASE \r\n                    WHEN result = 'Approved' THEN 1\r\n                    WHEN result = 'Rejected' THEN 0\r\n                    ELSE NULL\r\n                END\r\n            ) > 0.5 THEN 'Approved'\r\n        WHEN AVG(\r\n                CASE \r\n                    WHEN result = 'Approved' THEN 1\r\n                    WHEN result = 'Rejected' THEN 0\r\n                    ELSE NULL\r\n                END\r\n            ) <= 0.5 THEN 'Rejected'\r\n        ELSE 'Unknown'\r\n    END AS prediction_category\r\nFROM \r\n    loan_prediction\r\nWHERE \r\n    created_at >= NOW() - INTERVAL '320 minutes'\r\nGROUP BY \r\n    time\r\nORDER BY \r\n    time;\r\n"
    }
   ]
  }
 ]
}